title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://aleshkev.github.io/sako

remote_theme: just-the-docs/just-the-docs
